export const initialNodes = [
    {
        id: "candidate",
        type: "input",
        position: { x: 500, y: 50 },
        data: { label: "Candidate" },
        style: {
            background: "#ffffff",
            color: "#1e293b",
            border: "2px solid #cbd5e1",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "160px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(15, 23, 42, 0.08)",
        },
    },
    {
        id: "join-interview",
        type: "default",
        position: { x: 500, y: 170 },
        data: { label: "Join Interview" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "interview-session",
        type: "default",
        position: { x: 500, y: 290 },
        data: { label: "Interview Session" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "tab-switch",
        type: "default",
        position: { x: 500, y: 410 },
        data: { label: "Tab Switch Detected" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "switch-count",
        type: "default",
        position: { x: 500, y: 530 },
        data: { label: "Switch Count" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "warning",
        type: "default",
        position: { x: 250, y: 680 },
        data: { label: "1st / 2nd → Warning & Continue" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "terminate",
        type: "default",
        position: { x: 750, y: 680 },
        data: { label: "3rd Switch → Terminate" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "redirect",
        type: "output",
        position: { x: 750, y: 810 },
        data: { label: "Redirect → My Interviews" },
        style: {
            background: "#fef2f2",
            color: "#b91c1c",
            border: "2px solid #f87171",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(239, 68, 68, 0.12)",
        },
    },
];