export const initialNodes = [
    {
        id: "calendar-start",
        type: "input",
        position: { x: 500, y: 50 },
        data: { label: "NextHire Calendar" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "160px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "hr-portal",
        type: "default",
        position: { x: 100, y: 200 },
        data: { label: "HR Portal" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "candidate-portal",
        type: "default",
        position: { x: 500, y: 200 },
        data: { label: "Candidate Portal" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "interviewer-portal",
        type: "default",
        position: { x: 900, y: 200 },
        data: { label: "Interviewer Portal" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "interview-data",
        type: "default",
        position: { x: 500, y: 350 },
        data: { label: "Interview Data" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "calendar-views",
        type: "default",
        position: { x: 500, y: 500 },
        data: { label: "Calendar Views" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "filters",
        type: "default",
        position: { x: 850, y: 500 },
        data: { label: "Status / Mode Filters" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "event-details",
        type: "output",
        position: { x: 500, y: 650 },
        data: { label: "Interview Details" },
         style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
];