export const initialNodes = [
    {
        id: "hr-portal",
        type: "input",
        position: { x: 500, y: 50 },
        data: { label: "HR Portal" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "160px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "custom-table",
        type: "default",
        position: { x: 500, y: 170 },
        data: { label: "Custom Table" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "table-data",
        type: "default",
        position: { x: 500, y: 290 },
        data: { label: "Table Data" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "table-operations",
        type: "default",
        position: { x: 500, y: 410 },
        data: { label: "Table Operations" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "excel-import",
        type: "default",
        position: { x: 850, y: 410 },
        data: { label: "Excel Import" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "updated-table",
        type: "default",
        position: { x: 500, y: 550 },
        data: { label: "Updated Table" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "save-export",
        type: "output",
        position: { x: 500, y: 690 },
        data: { label: "Save / Excel Export" },
        style: {
            background: "#ecfdf5",
            color: "#047857",
            border: "2px solid #34d399",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(16, 185, 129, 0.12)",
        },
    },
];