export const initialNodes = [
    {
        id: "api-start",
        type: "input",
        position: { x: 500, y: 40 },
        data: { label: "HR Portal" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "160px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "recruiters-page",
        type: "default",
        position: { x: 500, y: 180 },
        data: { label: "Recruiters Page" },
        style: {
            background: "#ffffff",
            color: "#1e293b",
            border: "2px solid #cbd5e1",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(15, 23, 42, 0.08)",
        },
    },
    {
        id: "add-recruiter",
        type: "default",
        position: { x: 80, y: 300 },
        data: { label: "Add Recruiter" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "recruiter-form",
        type: "default",
        position: { x: 920, y: 300 },
        data: { label: "Recruiter Form" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "post-recruiter",
        type: "default",
        position: { x: 80, y: 440 },
        data: { label: "POST /recruiters" },
        style: {
            background: "#ffffff",
            color: "#1e293b",
            border: "2px solid #cbd5e1",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(15, 23, 42, 0.08)",
        },
    },
    {
        id: "recruiter-created",
        type: "default",
        position: { x: 920, y: 440 },
        data: { label: "Recruiter Created" },
        style: {
            background: "#ffffff",
            color: "#1e293b",
            border: "2px solid #cbd5e1",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(15, 23, 42, 0.08)",
        },
    },
    {
        id: "get-recruiters",
        type: "default",
        position: { x: 80, y: 580 },
        data: { label: "GET /recruiters" },
        style: {
            background: "#f8fafc",
            color: "#7c3aed",
            border: "2px solid #a78bfa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "700",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(124, 58, 237, 0.12)",
        },
    },
    {
        id: "recruiter-displayed",
        type: "default",
        position: { x: 500, y: 720 },
        data: { label: "Recruiter Data Displayed" },
            style: {
                background: "#ecfdf5",
                color: "#047857",
                border: "2px solid #34d399",
                borderRadius: "12px",
                padding: "11px 22px",
                fontWeight: "600",
                fontSize: "13px",
                minWidth: "230px",
                textAlign: "center",
                boxShadow: "0 3px 10px rgba(16, 185, 129, 0.12)",
            },
    },
    {
        id: "edit-recruiter",
        type: "default",
        position: { x: 100, y: 900 },
        data: { label: "Edit → PATCH /recruiters/:id" },
        style: {
            background: "#fff7ed",
            color: "#c2410c",
            border: "2px solid #fb923c",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(249, 115, 22, 0.12)",
        },
    },
    {
        id: "update-status",
        type: "default",
        position: { x: 500, y: 900 },
        data: { label: "Status → PATCH /recruiters/:id" },
        style: {
            background: "#fefce8",
            color: "#a16207",
            border: "2px solid #facc15",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(234, 179, 8, 0.12)",
        },
    },
    {
        id: "delete-recruiter",
        type: "default",
        position: { x: 900, y: 900 },
        data: { label: "Delete → DELETE /recruiters/:id" },
        style: {
            background: "#fef2f2",
            color: "#b91c1c",
            border: "2px solid #f87171",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(239, 68, 68, 0.12)",
        },
    },
];