export const initialNodes = [
    {
        id: "hr-portal",
        type: "input",
        position: { x: 500, y: 50 },
        data: { label: "HR Portal" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "160px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "analytics-dashboard",
        type: "default",
        position: { x: 500, y: 170 },
        data: { label: "Analytics Dashboard" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "time-period",
        type: "default",
        position: { x: 500, y: 290 },
        data: { label: "Time Period Filter" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "selected-data",
        type: "default",
        position: { x: 500, y: 410 },
        data: { label: "Selected Period Analytics Data" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "statistics",
        type: "default",
        position: { x: 180, y: 570 },
        data: { label: "Analytics Statistics" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "charts",
        type: "default",
        position: { x: 500, y: 570 },
        data: { label: "Recharts Visualizations" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "area-chart",
        type: "default",
        position: { x: 850, y: 500 },
        data: { label: "Applications & Hires — Area Chart" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "bar-chart",
        type: "default",
        position: { x: 850, y: 620 },
        data: { label: "Recruitment Funnel — Bar Chart" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "pie-chart",
        type: "default",
        position: { x: 850, y: 740 },
        data: { label: "Acquisition Channels — Pie Chart" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
    {
        id: "analytics-output",
        type: "output",
        position: { x: 500, y: 850 },
        data: { label: "Visual Analytics Dashboard" },
        style: {
            background: "#eff6ff",
            color: "#1d4ed8",
            border: "2px solid #60a5fa",
            borderRadius: "12px",
            padding: "11px 22px",
            fontWeight: "600",
            fontSize: "13px",
            minWidth: "230px",
            textAlign: "center",
            boxShadow: "0 3px 10px rgba(37, 99, 235, 0.12)",
        },
    },
];